version: "3.7"
services:
  db_mysql:
    build:
      context: ./mysql
      dockerfile: ./mysql.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_USER: exion
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_DATABASE: exion
    secrets:
      - mysql_secret
    ports:
      - "3306:3306"
    volumes:
      - "db:/var/lib/mysql"


secrets:
  mysql_secret:
    file: mysql_secret.txt

volumes:
  db: